# Generated by Django 4.2.9 on 2024-02-07 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('management_type', models.CharField(max_length=255)),
                ('address_old', models.CharField(max_length=255)),
                ('address_new', models.CharField(max_length=255)),
                ('latitude', models.CharField(max_length=255)),
                ('longitude', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=255)),
                ('operating_organization', models.CharField(max_length=255)),
                ('homepage', models.CharField(max_length=255)),
                ('amenities', models.CharField(max_length=255)),
                ('open_workday', models.CharField(max_length=255)),
                ('close_workday', models.CharField(max_length=255)),
                ('open_holiday', models.CharField(max_length=255)),
                ('close_holiday', models.CharField(max_length=255)),
                ('closed', models.CharField(max_length=255)),
                ('fee_adult', models.CharField(max_length=255)),
                ('fee_youth', models.CharField(max_length=255)),
                ('fee_child', models.CharField(max_length=255)),
                ('fee_info', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('transportation_info', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Galleries',
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('data', models.FileField(upload_to='imports/', verbose_name='uploaded_file')),
            ],
            options={
                'verbose_name_plural': 'Logs',
            },
        ),
    ]
