# Generated by Django 4.2.9 on 2024-02-07 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='fee_info',
            field=models.TextField(),
        ),
    ]
